server:
  port: 8090
  servlet:
    context-path: /tmall
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


